//External Imports
import {
  User,
  Mail,
  Phone,
  Calendar,
  Link2,
  Globe,
  MapPin,
} from "lucide-react";

export const FORM_FIELDS = [
  {
    id: "fullName",
    label: "Full Name",
    required: true,
    icon: User,
    placeholder: "John Doe",
    span: "half",
    fieldType: "Short Text",
    fieldSize: "Normal",
  },
  {
    id: "email",
    label: "Email Address",
    required: true,
    icon: Mail,
    placeholder: "example@gmail.com",
    span: "half",
    fieldType: "Email",
    fieldSize: "Normal",
  },
  {
    id: "phone",
    label: "Phone Number",
    required: true,
    icon: Phone,
    placeholder: "+62 812-1234-1234",
    span: "half",
    fieldType: "String",
    fieldSize: "Normal",
  },
  {
    id: "dob",
    label: "Date of Birth",
    required: true,
    icon: Calendar,
    placeholder: "YYYY-MM-DD",
    span: "half",
    fieldType: "Date Picker",
    fieldSize: "Normal",
  },
  {
    id: "linkedin",
    label: "LinkedIn Profile",
    required: true,
    icon: Link2,
    placeholder: "linkedin.com/in/yourname",
    span: "full",
    fieldType: "String",
    fieldSize: "Normal",
    description: "",
    minChars: "10",
    maxChars: "100",
    helpText: "",
    cssClass: "linkedin-field",
  },
  {
    id: "portfolio",
    label: "Portfolio",
    required: true,
    icon: Globe,
    placeholder: "www.yourportfolio.com",
    span: "full",
    fieldType: "Short Text",
    fieldSize: "Normal",
  },
  {
    id: "address",
    label: "Current Address",
    required: false,
    icon: MapPin,
    placeholder: "123 Evergreen Terrace, Apartment 00B",
    span: "full",
    type: "textarea",
    fieldType: "Paragraph",
    fieldSize: "Normal",
  },
];

export const FIELD_TYPE_PRESETS = {
  Password: {
    label: "Password",
    placeholder: "Enter your password",
    showDescription: false,
    required: false,
  },
  Email: {
    label: "Email",
    placeholder: "Enter your email",
    showDescription: false,
    required: false,
  },
};
